#!/bin/bash

mkdir -p dist
rm dist/* 



echo "" > dist/taskmonitor_part1.uc.js

echo """
// !! NOTE ! WARN ! This file is generated by build script. !! NOTE WARN !
// !! WARN NOTE !!! Do NOT edit this file !!! !!! WARN ! NOTE !
// !!! NOTE WARN Edit the source file !! !!! NOTE ! WARN !
"""  >> dist/taskmonitor_part1.uc.js

./include.py >> dist/taskmonitor_part1.uc.js

echo """
// !! NOTE ! WARN ! This file is generated by build script. !! NOTE WARN !
// !! WARN NOTE !!! Do NOT edit this file !!! !!! WARN ! NOTE !
// !!! NOTE WARN Edit the source file !! !!! NOTE ! WARN !
"""  >> dist/taskmonitor_part1.uc.js



cp src/taskmonitor_part2.uc.js.sys.mjs dist/

cp src/taskmonitor_part3_clearMemoryPeriodically.uc.js dist/taskmonitor_part3_clearMemoryPeriodically.uc.js
