#!/bin/bash

mkdir -p dist
rm dist/*


WARNING_MSG="""
// !! NOTE ! WARN ! This file is generated by build script. !! NOTE WARN !
// !! WARN NOTE !!! Do NOT edit this file !!! !!! WARN ! NOTE !
// !!! NOTE WARN Edit the source file !! !!! NOTE ! WARN !
"""


echo "" > dist/taskmonitor_part1.uc.js
echo "$WARNING_MSG" >> dist/taskmonitor_part1.uc.js
./include.py >> dist/taskmonitor_part1.uc.js
echo "$WARNING_MSG" >> dist/taskmonitor_part1.uc.js

echo "" > dist/taskmonitor_part2.uc.js.sys.mjs
echo "$WARNING_MSG" >> dist/taskmonitor_part2.uc.js.sys.mjs
cat src/taskmonitor_part2.uc.js.sys.mjs >> dist/taskmonitor_part2.uc.js.sys.mjs
echo "$WARNING_MSG" >> dist/taskmonitor_part2.uc.js.sys.mjs

echo "" > dist/taskmonitor_part3_clearMemoryPeriodically.uc.js
echo "$WARNING_MSG" >> dist/taskmonitor_part3_clearMemoryPeriodically.uc.js
cat src/taskmonitor_part3_clearMemoryPeriodically.uc.js >> dist/taskmonitor_part3_clearMemoryPeriodically.uc.js
echo "$WARNING_MSG" >> dist/taskmonitor_part3_clearMemoryPeriodically.uc.js